-- Create routes table
CREATE TABLE IF NOT EXISTS public.routes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.routes ENABLE ROW LEVEL SECURITY;

-- Create policy for public access (read/write)
DROP POLICY IF EXISTS "Enable all access for public" ON public.routes;

CREATE POLICY "Enable all access for public" ON public.routes
    FOR ALL
    USING (true)
    WITH CHECK (true);

-- Grant permissions to anon and authenticated roles
GRANT ALL ON TABLE public.routes TO anon;
GRANT ALL ON TABLE public.routes TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE routes_id_seq TO anon;
GRANT USAGE, SELECT ON SEQUENCE routes_id_seq TO authenticated;
